package interfaz;

import vistas.VistaListadenoticiasquenoestanenlaseccion_item;

public class Lista_de_noticias_que_no_estan_en__la_seccion_item extends VistaListadenoticiasquenoestanenlaseccion_item{
	public Lista_de_noticias_que_no_estan_en__la_seccion _lista_de_noticias_que_no_estan_en__la_seccion;
	tabla.Noticia _noticia;
	public Lista_de_noticias_que_no_estan_en__la_seccion_item(Lista_de_noticias_que_no_estan_en__la_seccion _lista_de_noticias_que_no_estan_en_la_seccion, tabla.Noticia noticia) {
		super();
		this._noticia = noticia;

		this._lista_de_noticias_que_no_estan_en__la_seccion = _lista_de_noticias_que_no_estan_en_la_seccion;
	}
}