package interfaz;

import vistas.VistaListadenoticiasquenoestanenlaseccion_item;

public class Lista_de_noticias_que_no_estan_en__la_seccion_item extends VistaListadenoticiasquenoestanenlaseccion_item{
	public Lista_de_noticias_que_no_estan_en__la_seccion _lista_de_noticias_que_no_estan_en__la_seccion;
	
	public Lista_de_noticias_que_no_estan_en__la_seccion_item(Lista_de_noticias_que_no_estan_en__la_seccion _lista_de_noticias_que_no_estan_en_la_seccion) {
		super();
		this._lista_de_noticias_que_no_estan_en__la_seccion = _lista_de_noticias_que_no_estan_en_la_seccion;
	}
}